
import { StyleSheet } from "react-native";
import theme from "../constants/theme";

const globalStyles = StyleSheet.create({
    safeArea: {
    flex: 1,
    backgroundColor: theme.colors.surface, // fondo gris claro
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    padding: theme.spacing.lg,
    justifyContent: "center",
  },
   logoContainer: {
    alignItems: "center",
    marginBottom: theme.spacing.lg,
  },
  logo: {
    width: 100,
    height: 100,
    resizeMode: "contain",
    marginBottom: theme.spacing.xl,
  },
  label: {
    fontSize: theme.typography.fontSize.small,
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.medium,
    marginBottom: 4,
    marginTop: theme.spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.sm,
    fontSize: theme.typography.fontSize.medium,
    fontFamily: theme.typography.fontFamily.regular,
    backgroundColor: "#FFFFFF",
    marginBottom: theme.spacing.sm,
  },
  loginButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
   primaryButton: {
    backgroundColor: theme.colors.primary,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.md,
  },
  buttonText: {
    color: theme.colors.background,
    fontSize: theme.typography.fontSize.medium,
    fontFamily: theme.typography.fontFamily.bold,
  },
  forgotPassword: {
    color: theme.colors.textSecondary,
    fontSize: theme.typography.fontSize.small,
    textAlign: "center",
    marginTop: theme.spacing.sm,
    textDecorationLine: "underline",
  },
  registerText: {
    textAlign: "center",
    color: theme.colors.textSecondary,
    marginTop: theme.spacing.lg,
  },
  textLink: {
    color: theme.colors.primary,
    fontWeight: "bold",
  },
  socialButton: {
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: theme.borderRadius.md,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
    marginTop: theme.spacing.sm,
  },
  socialText: {
    fontSize: theme.typography.fontSize.medium,
    fontFamily: theme.typography.fontFamily.regular,
    color: theme.colors.textPrimary,
    marginLeft: theme.spacing.sm,
    flex: 1,
    textAlign: "center",
  },
   title: {
    fontSize: theme.typography.fontSize.title,
    fontFamily: theme.typography.fontFamily.regular,
    color: theme.colors.textPrimary,
    textAlign: "center",
    marginBottom: theme.spacing.lg,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)", // fondo gris semitransparente
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacing.lg,
  },
  modalContainer: {
    backgroundColor: theme.colors.background,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    width: "100%",
    maxWidth: 320,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: theme.typography.fontSize.title,
    fontFamily: theme.typography.fontFamily.regular,
    fontWeight: "bold",
    marginBottom: theme.spacing.sm,
    color: theme.colors.textSecondary,
  },
  modalText: {
    fontSize: theme.typography.fontSize.small,
    fontFamily: theme.typography.fontFamily.regular,
    color: theme.colors.textSecondary,
    textAlign: "center",
    marginBottom: theme.spacing.md,
  },
  pickerContainer: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "space-between",
  borderWidth: 1,
  borderColor: theme.colors.primary,
  borderRadius: theme.borderRadius.md,
  backgroundColor: theme.colors.background,
  paddingHorizontal: theme.spacing.md,
  paddingVertical: theme.spacing.sm,
  marginBottom: theme.spacing.md,
},

pickerText: {
  fontSize: theme.typography.fontSize.medium,
  fontFamily: theme.typography.fontFamily.medium,
  color: theme.colors.surface,
  flex: 1,
},
  errorText: {
    color: theme.colors.error,
    fontSize: theme.typography.fontSize.small,
    marginTop: theme.spacing.sm,
    textAlign: "center",
  },
  successContainer: {
  backgroundColor: theme.colors.background,
  borderRadius: theme.borderRadius.lg,
  padding: theme.spacing.lg,
  alignItems: "center",
  width: "100%",
  maxWidth: 320,
},
successTitle: {
  fontSize: theme.typography.fontSize.title,
  fontFamily: theme.typography.fontFamily.regular,
  color: theme.colors.textPrimary,
  textAlign: "center",
  marginTop: theme.spacing.sm,
},
successLink: {
  color: theme.colors.primary,
  fontSize: theme.typography.fontSize.small,
  textDecorationLine: "underline",
  marginTop: theme.spacing.md,
},
});

export default globalStyles;
